//------------------------------------------------------------------------
// Copyright(c) 2025 Daniel Wittmann.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"VSTEffectPlugIn.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"VSTEffectPlugIn VST3 (64Bit)"
#else
#define stringFileDescription	"VSTEffectPlugIn VST3"
#endif
#define stringCompanyName		"Daniel Wittmann\0"
#define stringLegalCopyright	"Copyright(c) 2025 Daniel Wittmann."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
